export const UI_UX_SKILLS = [
  "12-Column Grid",
  "60-30-10 Rule",
  "8-Point Spacing Rhythm",
  "A/B Testing",
  "A/B/n Testing & Multivariate Analysis",
  "Accessible Components",
  "Accessibility (A11y) & WCAG 2.2/3.0 Compliance",
  "Active & Disabled Component States",
  "Adaptive & Responsive Layouts",
  "Adaptive UI",
  "Affordance & Signifier Design",
  "Affinity Diagramming & Mapping",
  "AI Chatbot UI Components",
  "AI-Driven Generative UI Patterns",
  "Algorithmic Transparency UX",
  "Ambient Computing Interface Design",
  "AR/VR/XR Spatial UI Design",
  "Atomic Design Methodology",
  "Behavioral Design & Nudge Architecture",
  "Benchmarking & Competitive Analysis",
  "Biometric UX Interfaces",
  "Brain-Computer Interface (BCI) UX Design",
  "Card Sorting",
  "Clickstream & Heatmap Analysis",
  "Cognitive Load Optimization",
  "Color Contrast Checkers",
  "Color Palettes",
  "Color Theory",
  "Component Libraries",
  "Component States",
  "Context-Aware Interaction Systems",
  "Conversion Rate Optimization (CRO) UX",
  "Cross-Cultural UX Design",
  "Dark & Light Mode Theme Systems",
  "Dark Pattern Identification & Auditing",
  "Data Visualization Ergonomics",
  "Design Constraint Packages",
  "Design Engineering Control Blocks",
  "Design Handoff & Specs Documentation",
  "Design Operations (DesignOps)",
  "Design Principles",
  "Design System Architecture",
  "Design Systems & Governance",
  "Design Token Automation",
  "Design Tokens",
  "Desktop Viewports",
  "Digital Accessibility Auditing",
  "Dynamic & Adaptive Layout Engines",
  "Ergonomic Layout Design",
  "Ethnographic Field Research",
  "Eye-Tracking & Foveated UX Analysis",
  "Figma",
  "Flexbox",
  "Form Design & Input Ergonomics",
  "Frontend Plans",
  "frontend-design (Constraint System)",
  "Gamification Frameworks & UX Mechanics",
  "Gestalt Principles of Visual Perception",
  "Gesture-Based Interactions",
  "Grid Layout",
  "Grid Systems",
  "Haptic Feedback & Tactile UX",
  "Heuristic Evaluation",
  "High-Fidelity Prototyping",
  "Human Factors Engineering",
  "Human-Centered Design (HCD)",
  "Iconography & Visual Metaphors",
  "Image & Asset Optimization for UI",
  "impeccable (Constraint System)",
  "Information Architecture (IA)",
  "Information Density Management",
  "Interaction Design (IxD)",
  "Interaction States",
  "Keyframe & Timeline Animation",
  "Layout Systems",
  "Line Heights",
  "Liquid Layouts",
  "Low-Fidelity Wireframing",
  "Micro-gestures & Spatial Motion Tracking",
  "Micro-interactions",
  "Microcopy & UX Writing",
  "Mobile Viewports",
  "Mobile-First Strategy",
  "Motion Design & Micro-animations",
  "Multi-Device Experience (MDX) Strategy",
  "Multimodal User Interfaces",
  "Neuromarketing & Psycho-Visual Triggers",
  "Persona Development & Archetyping",
  "Progressive Disclosure",
  "Prototyping (Figma/ProtoPie/Principle)",
  "Psychological UX Principles (Fitts's Law, Hick's Law, Jakob's Law, Miller's Law)",
  "Quantitative & Qualitative UX Research",
  "Rapid Prototyping",
  "Responsive Design",
  "Responsive Typography",
  "Scenario Mapping",
  "Service Design Blueprinting",
  "Shadcn/ui",
  "Spatial Composition",
  "Specialised UI Constraint Blocks",
  "Storyboarding",
  "System Usability Scale (SUS) Evaluation",
  "Tablet Viewports",
  "Task Analysis & Workflow Optimization",
  "Thermal & Bio-Feedback UX",
  "Tree Testing",
  "Type Scales",
  "Typography",
  "Typography Hierarchy",
  "UI Animation",
  "UI Architecture",
  "UI Auditing & Design Debt Management",
  "UI Design",
  "Usability Testing",
  "User Acceptance Testing (UAT) Support",
  "User Journey Mapping",
  "User Personas",
  "User Preference Systems",
  "User Research",
  "User-Centered Design",
  "UX Analytics & HEART Framework Metrics",
  "UX Auditing",
  "UX Design",
  "UX Governance & Scalability",
  "UX Plans",
  "UX Strategy",
  "Visual Components",
  "Visual Hierarchy",
  "Voice User Interface (VUI) & Conversational UX",
  "Wireframing",
  "Zero-UI / Invisible UI Systems",
] as const;

export const TWO_D_THREE_D_SKILLS = [
  "2D Animation",
  "2D Crowd Simulation",
  "2D Frame-by-Frame Fluid/Smoke FX",
  "2D Particle Systems",
  "2D Rigging",
  "2D Vector-Math Driven Animation",
  "3-Point Lighting",
  "3D Polygonal Modeling",
  "3D Real-Time Engine Optimization",
  "Abstract Expressionism",
  "Anticipation",
  "AR/VR/XR Spatial UI Design",
  "Art Deco",
  "Art Nouveau",
  "Auto-layout",
  "Bauhaus",
  "Bento Box UI",
  "Blend Shapes",
  "Blender",
  "Brutalism",
  "Camera Tracking",
  "Cel Shading",
  "Character Acting",
  "Character Rigging",
  "Cinema 4D",
  "Clipping Masks",
  "Cloth Simulation (Marvelous Designer)",
  "Color Contrast Checkers",
  "Color Grading",
  "Color Psychology",
  "Color Theory",
  "Comic/Pop Art",
  "Composition",
  "Concept Art Workflow",
  "Contextual Inquiry",
  "Corporate Memphis",
  "Creature FX (CFX)",
  "Custom Shader Programming (HLSL/GLSL)",
  "Cyberpunk Visual Style",
  "Datamoshing & Glitch Art",
  "Digital Sculpting (ZBrush)",
  "Easing (Ease In/Out)",
  "Editorial Design",
  "Environmental Graphics",
  "Eye-Tracking Analysis",
  "Facial Action Coding System (FACS) Rigging",
  "Figma",
  "Flat Design",
  "FLIP Fluid Dynamics",
  "Forward Kinematics (FK)",
  "Frame-by-Frame Traditional Animation",
  "Generative Art",
  "Gestalt Principles",
  "Gesture-Based Interactions",
  "Glassmorphism",
  "Global Illumination",
  "Grid Systems",
  "Hair & Fur Grooming (XGen)",
  "Hand-Drawn Animation",
  "Haptic & Tactile Feedback Design",
  "Hard Surface Modeling",
  "Heuristic Evaluation",
  "High-Fidelity Prototyping",
  "Houdini VEX & Procedural Generation",
  "Hyperrealism",
  "Iconography",
  "Information Architecture (IA)",
  "Inverse Kinematics (IK)",
  "Isometric Design",
  "Keyframe Animation",
  "Kinetic Typography",
  "LiDAR Scanning & Point Cloud Processing",
  "Line Art",
  "Lip Syncing",
  "Lottie/JSON Animation",
  "Low Poly Modeling",
  "Low-Fidelity Wireframing",
  "Material Design",
  "Matte Painting",
  "Maya",
  "Memphis Design",
  "Micro-animations",
  "Micro-interactions",
  "Minimalist Design",
  "Mobile-First Design",
  "Morphing",
  "Motion Capture (MoCap) Cleanup",
  "Motion Design",
  "Multi-pass Compositing",
  "Muscle Rigging",
  "Neobrutalism",
  "Neumorphism",
  "Node-Based Compositing",
  "Normal & Bump Mapping",
  "Parallax Scrolling",
  "Parametric Design",
  "Persona Creation",
  "Photo Manipulation",
  "Photogrammetry Workflow",
  "Photorealism",
  "Pixel Art",
  "Polygonal Modeling",
  "Pre-press Production",
  "Procedural 2D Animation",
  "Procedural Texturing",
  "Puppet Pin Rigging",
  "Pyrotechnics & Volumetrics",
  "Raymarching",
  "Real-Time Audio-Reactive Visuals",
  "Real-Time Rendering (Unreal Engine Nanite/Lumen)",
  "Rendering Engine Optimization",
  "Responsive Design",
  "Retopology",
  "Rigid & Soft Body Dynamics",
  "Rotoscoping",
  "Rubber Hose Animation",
  "Script-Driven Automated Rigging",
  "Scripting & Expressions (JavaScript/ExtendScript)",
  "Service Blueprinting",
  "Shader Graphs",
  "Smear Frames",
  "Spatial Composition",
  "Squash and Stretch",
  "Storyboarding",
  "Subsurface Scattering",
  "Surrealism",
  "Swiss Design",
  "Synthwave Style",
  "Texture Baking",
  "Timeline Management",
  "Toon Boom Harmony",
  "Typography",
  "UI Architecture",
  "UI Auditing",
  "Usability Testing",
  "User Flow Mapping",
  "UV Unwrapping & Mapping",
  "Vaporwave Style",
  "Vector Graphics",
  "Vellum Simulations",
  "Voice User Interface (VUI)",
  "Volumetric Rendering",
  "Walk Cycles",
  "Whiteboard Animation",
  "Wireframing",
  "Y2K Aesthetic",
] as const;

export const DESIGN_INTELLIGENCE_SKILLS = [
  ...UI_UX_SKILLS,
  ...TWO_D_THREE_D_SKILLS,
] as const;

const UNIVERSAL_QUALITY_GATES = [
  "Start from user tasks and information architecture, not decorative styling. Preserve real product behavior while rebuilding presentation around the target direction.",
  "Use a coherent layout system: establish container widths, responsive columns, a 12-column grid where appropriate, Flexbox/Grid deliberately, and an 8-point spacing rhythm with optical exceptions only when justified.",
  "Use a deliberate color system. Apply color theory and the 60-30-10 distribution when suitable, preserve semantic colors, support light/dark modes when the product exposes them, and never sacrifice legibility to style.",
  "Meet WCAG 2.2 AA as a minimum practical target: semantic structure, keyboard access, visible focus, meaningful labels, non-color-only status, adequate contrast, reduced-motion support, touch targets, zoom/reflow resilience, and accessible error/validation states. Treat emerging WCAG 3.0 concepts as forward-looking guidance rather than claiming formal compliance.",
  "Design every relevant state: default, hover, focus-visible, active/pressed, selected, disabled, loading, empty, success, warning, error, destructive confirmation, offline/retry, and permission-denied where applicable.",
  "Optimize cognitive load with progressive disclosure, clear grouping, strong visual hierarchy, concise microcopy, predictable navigation, and Fitts/Hick/Jakob/Miller principles without manipulative dark patterns.",
  "Treat forms as task flows: persistent labels, useful defaults, input modes, autocomplete, field grouping, inline validation, explicit required/optional status, recoverable errors, and efficient keyboard/mobile entry.",
  "Design mobile-first, then tablet and desktop. Verify small-phone, large-phone, tablet, laptop, desktop, wide-desktop and high-density data cases; use fluid typography and liquid/adaptive layouts without horizontal overflow.",
  "Use design tokens and component architecture consistently. Avoid one-off magic values when a token or reusable component/state can express the decision. Preserve compatibility with the project's existing component framework when it is functional.",
  "When Tailwind CSS v4 is present, use valid CSS-first architecture: keep @import statements before normal rules; use @import \"tailwindcss\" or decomposed Tailwind imports where each layer(...) contains exactly one layer name; define regular runtime variables in :root/.dark; keep @theme/@theme inline top-level for variables that should generate utilities; and define custom utility classes with @utility when variant support is required. Never place naked declarations directly inside @layer base.",
  "Preserve an existing semantic CSS-variable API even while replacing its visual values. If the project already exposes tokens such as --background, --foreground, --card, --primary, --secondary, --muted, --accent, --destructive, --border, --input, --ring, --chart-* or --radius, keep those names resolved for direct consumers and map new art-direction tokens behind them instead of deleting the API.",
  "Token aliases must stay semantically correct in every theme. In dark mode, body/heading/sidebar foreground tokens must remain light enough against dark surfaces; bright secondary/accent fills need dark readable foregrounds; muted foregrounds must remain readable on muted surfaces; and focus indicators must reach at least 3:1 against adjacent colors. Target WCAG AA 4.5:1 for ordinary text pairs, including primary/destructive button labels and default links.",
  "Keep input/control boundary tokens visually distinct from surface/fill tokens. Do not map --input/--color-input to the same resolved color as --background, --card or a generic surface fill when that token is used by border-input or control outlines.",
  "Use motion only to communicate hierarchy, causality, continuity, feedback, orientation or delight. Prefer transform/opacity, sensible easing, short durations, interruption safety, and prefers-reduced-motion fallbacks. Never gate essential information behind animation.",
  "Apply Gestalt, affordance/signifier, ergonomic and human-factors principles. Interactive elements must look interactive; hierarchy must remain understandable without relying on novelty.",
  "For data-heavy interfaces, optimize scan paths, density, alignment, comparison, labeling, chart readability, colorblind safety, table responsiveness, and progressive detail instead of decorating data.",
  "For conversion surfaces, optimize comprehension, trust, CTA hierarchy and friction ethically. Do not invent scarcity, fake social proof, forced continuity, confirmshaming, obstruction or other dark patterns.",
  "For AI/agentic interfaces, make model status, uncertainty, provenance where available, permissions, destructive actions, reversibility, generated-vs-user content and automation boundaries legible. Never imply invisible certainty.",
  "For multimodal, spatial, biometric, ambient, haptic, VUI or zero-UI concepts, always provide a visible/operable fallback path and respect privacy, consent, safety and accessibility constraints.",
  "Use research methods as reasoning tools when direct studies are unavailable: infer hypotheses, identify what should be tested, and never fabricate A/B results, heatmaps, eye-tracking, SUS scores, analytics, interviews or user-research findings.",
  "Audit the final result for design debt: inconsistent spacing, duplicate component patterns, inaccessible color, missing states, broken hierarchy, unclear copy, excessive density, unnecessary decoration, brittle breakpoints and performance-heavy effects.",
] as const;

const VISUAL_2D_3D_GATES = [
  "When 2D/3D is relevant, establish composition, focal hierarchy, camera/perspective, lighting, material response, color grade and motion language before adding detail.",
  "For real-time 3D/WebGL, protect frame time: budget geometry, draw calls, lights, shadow maps, post-processing, texture memory and DPR; use LOD/instancing/baking/compression where appropriate and provide non-WebGL fallbacks.",
  "Use PBR/material concepts correctly when photorealism is intended: albedo/base color, roughness, metalness, normals, bump/displacement, AO, emissive, subsurface/transmission only where physically plausible.",
  "For shaders/procedural visuals, keep GLSL/HLSL/shader-graph logic numerically stable, resolution-aware, time-step safe and performant; avoid effects that compromise text contrast or input responsiveness.",
  "For animation, apply anticipation, squash/stretch, arcs, follow-through/overlap, timing, spacing, easing and staging selectively. Interface motion should remain subtler than character animation unless the chosen direction explicitly calls for expressive motion.",
  "For particles, fluids, cloth, crowds, volumetrics, hair/fur or rigid/soft-body effects, treat simulation as a visual system with deterministic fallbacks and performance ceilings rather than an uncontrolled decoration layer.",
  "For 2D/vector assets, keep paths economical, clipping/masks intentional, rasterization crisp, animation compositing-friendly, and export formats appropriate (SVG/Lottie/raster/video) for the target runtime.",
  "For scanned/photogrammetry/LiDAR assets, account for cleanup, retopology, UVs, texture baking, normals, scale/origin, occlusion and runtime simplification before use in an interactive product.",
  "Use art-direction knowledge—Bauhaus, Swiss, Deco, Nouveau, Pop, Memphis, Brutalism, Cyberpunk, Vaporwave, Synthwave, Y2K, surrealism and related movements—as structural visual grammar, not superficial filters.",
] as const;

function detectSpecialisms(fileName: string, source: string, instruction = "") {
  const haystack = `${fileName}\n${source.slice(0, 120_000)}\n${instruction}`.toLowerCase();
  const matches: string[] = [];

  if (/three|@react-three|webgl|canvas|glsl|shader|fragment|vertex|r3f|babylon|aframe|model-viewer|gltf|glb|obj\b|fbx|usdz/.test(haystack)) {
    matches.push("real-time 3D, spatial composition, shader/material, camera/lighting and rendering optimization");
  }
  if (/svg|lottie|canvas|animation|keyframe|framer-motion|motion\.|gsap|timeline|parallax|scrolltrigger/.test(haystack)) {
    matches.push("2D/motion design, vector animation, easing, keyframes, timeline management and reduced-motion behavior");
  }
  if (/chart|graph|table|dashboard|analytics|metric|sparkline|plot|d3\b|recharts|echarts/.test(haystack)) {
    matches.push("data visualization ergonomics, information density management, comparison and scan-path optimization");
  }
  if (/form|input|select|textarea|checkbox|radio|validation|signup|checkout|login|register/.test(haystack)) {
    matches.push("form ergonomics, validation, error recovery, conversion clarity and accessible component states");
  }
  if (/chat|assistant|agent|generative|ai-|llm|copilot|prompt|conversation/.test(haystack)) {
    matches.push("AI-native, conversational, agentic, algorithmic-transparency and multimodal UX");
  }
  if (/tailwindcss|@theme\b|@utility\b|@custom-variant|@source\b/.test(haystack)) {
    matches.push("Tailwind v4 CSS-first architecture, theme-variable namespaces, custom utilities, variants, semantic token compatibility and cascade/layer correctness");
  }
  if (/aria-|role=|tabindex|focus|keyboard|screenreader|sr-only/.test(haystack)) {
    matches.push("accessibility auditing, keyboard/focus systems and semantic interaction design");
  }
  if (/video|audio|mic|voice|speech|webxr|xr|ar\b|vr\b|gesture|haptic|biometric/.test(haystack)) {
    matches.push("multimodal, VUI, gesture, spatial, haptic and privacy-aware interaction design");
  }

  return matches.length > 0 ? matches : ["general product UI/UX architecture, accessibility, responsive systems and visual hierarchy"];
}

export function buildDesignIntelligenceContext(opts: {
  fileName: string;
  source: string;
  style?: string | null;
  instruction?: string;
}) {
  const specialisms = detectSpecialisms(opts.fileName, opts.source, opts.instruction ?? "");
  const uiSkills = UI_UX_SKILLS.join("; ");
  const visualSkills = TWO_D_THREE_D_SKILLS.join("; ");

  return [
    "DESIGN INTELLIGENCE OPERATING SYSTEM",
    "Use the following capabilities as an expert knowledge base. Apply every capability when relevant; do not force irrelevant techniques into the interface. Never fabricate research evidence, test results, analytics, biometric findings, eye-tracking, user interviews, A/B outcomes or tool execution that did not actually occur.",
    opts.style ? `Target design direction: ${opts.style}. The direction controls art direction; the quality gates below control correctness.` : "No fixed art direction was supplied; infer the requested visual direction from the user's instruction while preserving product coherence.",
    `Detected priority disciplines for this file: ${specialisms.join("; ")}.`,
    "UNIVERSAL PRODUCT QUALITY GATES:\n- " + UNIVERSAL_QUALITY_GATES.join("\n- "),
    "2D / 3D / MOTION QUALITY GATES WHEN RELEVANT:\n- " + VISUAL_2D_3D_GATES.join("\n- "),
    `FULL UI/UX COMPETENCY REGISTRY (${UI_UX_SKILLS.length} entries; none may be omitted from the engine's knowledge base):\n${uiSkills}`,
    `FULL 2D/3D COMPETENCY REGISTRY (${TWO_D_THREE_D_SKILLS.length} entries; none may be omitted from the engine's knowledge base):\n${visualSkills}`,
    "FINAL INTERNAL REVIEW BEFORE OUTPUT: verify task flow, IA, visual hierarchy, responsive behavior, typography, spacing rhythm, color/contrast, component/state completeness, affordances, forms, keyboard/focus behavior, motion/reduced-motion, performance, content clarity, ethical UX, design-system consistency, and any relevant 2D/3D rendering constraints. Fix defects before returning code.",
  ].join("\n\n");
}


export function buildDesignQaContext(opts: {
  fileName: string;
  source: string;
  style?: string | null;
  instruction?: string;
}) {
  const specialisms = detectSpecialisms(opts.fileName, opts.source, opts.instruction ?? "");
  return [
    "REZYN DESIGN RELEASE QA CONTEXT",
    opts.style
      ? `Target direction: ${opts.style}. Verify that the direction is unmistakable without compromising correctness.`
      : "Verify the requested visual direction while preserving product coherence.",
    `Priority disciplines: ${specialisms.join("; ")}.`,
    "UNIVERSAL RELEASE GATES:\n- " + UNIVERSAL_QUALITY_GATES.join("\n- "),
    "2D / 3D / MOTION RELEASE GATES WHEN RELEVANT:\n- " + VISUAL_2D_3D_GATES.join("\n- "),
    "QA must stay evidence-based: do not invent test results, analytics, research, performance measurements or requirements absent from source/project plan.",
  ].join("\n\n");
}
