import { createFileRoute } from "@tanstack/react-router";
import { LegalPage } from "@/components/site/LegalPage";

export const Route = createFileRoute("/legal/ai-disclosure")({
  head: () => ({
    meta: [
      { title: "AI Disclosure — how Rezyn uses AI | Rezyn" },
      { name: "description", content: "An honest explanation of how Rezyn uses AI to redesign files, what it checks, and what it can still get wrong." },
      { property: "og:title", content: "AI Disclosure | Rezyn" },
      { property: "og:description", content: "How Rezyn uses AI, what it verifies, and its real limitations." },
      { property: "og:type", content: "article" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: () => (
    <LegalPage
      index="03"
      title="AI Disclosure"
      summary="Rezyn is built on top of third-party AI models — the same family of technology behind popular chatbots. Here's exactly what we add around them, and what they can still get wrong."
      sections={[
        {
          heading: "Yes, it's AI",
          body: (
            <p>
              Redesigned files are generated by large language models accessed through an AI provider. No human designer
              reviews your files. We say this plainly because you deserve to know.
            </p>
          ),
        },
        {
          heading: "What Rezyn does around the model",
          body: (
            <ul>
              <li>Processes your project <strong>one file at a time</strong>, so large projects aren't squeezed into one chat message.</li>
              <li>Gives every file the same <strong>style blueprint</strong> and a list of the other files in the project, to keep the result consistent.</li>
              <li>Instructs the model to keep behaviour — routes, event handlers, data bindings, forms, IDs — and change presentation only.</li>
              <li>Runs a <strong>similarity check</strong> that rejects output too close to the original look.</li>
              <li>Runs a <strong>second AI review pass</strong> on each result and retries when it finds blocking issues.</li>
              <li>Records a visible error on any file that still fails, instead of silently returning it.</li>
            </ul>
          ),
        },
        {
          heading: "What it can still get wrong",
          body: (
            <ul>
              <li>Code may fail to compile, or behave differently from the original.</li>
              <li>The automated review is itself AI — it reduces mistakes but can miss them.</li>
              <li>Only text and code files are redesigned. Images, fonts and other binary files are skipped and are not in the download.</li>
              <li>Very large files may be rejected for size.</li>
              <li>Accessibility and contrast are checked by instruction, not by a certified audit.</li>
            </ul>
          ),
        },
        {
          heading: "Your responsibility",
          body: (
            <p>
              Treat output as a strong first draft from a fast collaborator. Keep your originals, compare the files, run your
              tests and check the result in a browser before shipping.
            </p>
          ),
        },
        {
          heading: "Training",
          body: <p>Your files are sent to AI providers only to generate your redesign. Rezyn does not use them to train models.</p>,
        },
      ]}
    />
  ),
});
