/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StylesRouteImport } from './routes/styles'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as WorkRouteImport } from './routes/work'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as LegalAcceptableUseRouteImport } from './routes/legal.acceptable-use'
import { Route as LegalAiDisclosureRouteImport } from './routes/legal.ai-disclosure'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdChatRouteImport } from './routes/projects.$projectId_.chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesRoute = StylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAcceptableUseRoute = LegalAcceptableUseRouteImport.update({
  id: '/legal/acceptable-use',
  path: '/legal/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAiDisclosureRoute = LegalAiDisclosureRouteImport.update({
  id: '/legal/ai-disclosure',
  path: '/legal/ai-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdChatRoute = ProjectsProjectIdChatRouteImport.update({
  id: '/projects/$projectId_/chat',
  path: '/projects/$projectId/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/styles': typeof StylesRoute
  '/trends': typeof TrendsRoute
  '/work': typeof WorkRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/ai-disclosure': typeof LegalAiDisclosureRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/legal/': typeof LegalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/chat': typeof ProjectsProjectIdChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/styles': typeof StylesRoute
  '/trends': typeof TrendsRoute
  '/work': typeof WorkRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/ai-disclosure': typeof LegalAiDisclosureRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/legal': typeof LegalIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/chat': typeof ProjectsProjectIdChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/styles': typeof StylesRoute
  '/trends': typeof TrendsRoute
  '/work': typeof WorkRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/ai-disclosure': typeof LegalAiDisclosureRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/legal/': typeof LegalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId_/chat': typeof ProjectsProjectIdChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/process'
    | '/services'
    | '/styles'
    | '/trends'
    | '/work'
    | '/legal/acceptable-use'
    | '/legal/ai-disclosure'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/projects/$projectId'
    | '/legal/'
    | '/projects/'
    | '/projects/$projectId/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/process'
    | '/services'
    | '/styles'
    | '/trends'
    | '/work'
    | '/legal/acceptable-use'
    | '/legal/ai-disclosure'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/projects/$projectId'
    | '/legal'
    | '/projects'
    | '/projects/$projectId/chat'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/process'
    | '/services'
    | '/styles'
    | '/trends'
    | '/work'
    | '/legal/acceptable-use'
    | '/legal/ai-disclosure'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/projects/$projectId'
    | '/legal/'
    | '/projects/'
    | '/projects/$projectId_/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
  StylesRoute: typeof StylesRoute
  TrendsRoute: typeof TrendsRoute
  WorkRoute: typeof WorkRoute
  LegalAcceptableUseRoute: typeof LegalAcceptableUseRoute
  LegalAiDisclosureRoute: typeof LegalAiDisclosureRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  LegalIndexRoute: typeof LegalIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdChatRoute: typeof ProjectsProjectIdChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles': {
      id: '/styles'
      path: '/styles'
      fullPath: '/styles'
      preLoaderRoute: typeof StylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/acceptable-use': {
      id: '/legal/acceptable-use'
      path: '/legal/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof LegalAcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/ai-disclosure': {
      id: '/legal/ai-disclosure'
      path: '/legal/ai-disclosure'
      fullPath: '/legal/ai-disclosure'
      preLoaderRoute: typeof LegalAiDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_/chat': {
      id: '/projects/$projectId_/chat'
      path: '/projects/$projectId/chat'
      fullPath: '/projects/$projectId/chat'
      preLoaderRoute: typeof ProjectsProjectIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
  StylesRoute: StylesRoute,
  TrendsRoute: TrendsRoute,
  WorkRoute: WorkRoute,
  LegalAcceptableUseRoute: LegalAcceptableUseRoute,
  LegalAiDisclosureRoute: LegalAiDisclosureRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  LegalIndexRoute: LegalIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdChatRoute: ProjectsProjectIdChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
